// Auto-generated by Supabase CLI — do not edit manually
// Project: fiskix (rqplobwsdbceuqhjywgt)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      alertas_fraude: {
        Row: {
          atualizado_em: string
          criado_em: string
          id: string
          id_cliente: string
          mes_ano: string
          motivo: Json
          resultado: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco: number
          status: Database["public"]["Enums"]["alerta_status"]
        }
        Insert: {
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_cliente: string
          mes_ano: string
          motivo?: Json
          resultado?: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco: number
          status?: Database["public"]["Enums"]["alerta_status"]
        }
        Update: {
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_cliente?: string
          mes_ano?: string
          motivo?: Json
          resultado?: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco?: number
          status?: Database["public"]["Enums"]["alerta_status"]
        }
        Relationships: [
          {
            foreignKeyName: "alertas_fraude_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      clientes: {
        Row: {
          ativo: boolean
          cil: string | null
          criado_em: string
          id: string
          id_subestacao: string
          lat: number | null
          lng: number | null
          morada: string
          nif: string | null
          nome_titular: string
          numero_conta: string | null
          numero_contador: string
          potencia_contratada_w: number | null
          telemovel: string | null
          tipo_tarifa: Database["public"]["Enums"]["tipo_tarifa"]
          unidade_comercial: string | null
        }
        Insert: {
          ativo?: boolean
          cil?: string | null
          criado_em?: string
          id?: string
          id_subestacao: string
          lat?: number | null
          lng?: number | null
          morada: string
          nif?: string | null
          nome_titular: string
          numero_conta?: string | null
          numero_contador: string
          potencia_contratada_w?: number | null
          telemovel?: string | null
          tipo_tarifa?: Database["public"]["Enums"]["tipo_tarifa"]
          unidade_comercial?: string | null
        }
        Update: {
          ativo?: boolean
          cil?: string | null
          criado_em?: string
          id?: string
          id_subestacao?: string
          lat?: number | null
          lng?: number | null
          morada?: string
          nif?: string | null
          nome_titular?: string
          numero_conta?: string | null
          numero_contador?: string
          potencia_contratada_w?: number | null
          telemovel?: string | null
          tipo_tarifa?: Database["public"]["Enums"]["tipo_tarifa"]
          unidade_comercial?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "clientes_id_subestacao_fkey"
            columns: ["id_subestacao"]
            isOneToOne: false
            referencedRelation: "subestacoes"
            referencedColumns: ["id"]
          },
        ]
      }
      configuracoes: {
        Row: {
          atualizado_em: string
          chave: string
          descricao: string | null
          valor: string
        }
        Insert: {
          atualizado_em?: string
          chave: string
          descricao?: string | null
          valor: string
        }
        Update: {
          atualizado_em?: string
          chave?: string
          descricao?: string | null
          valor?: string
        }
        Relationships: []
      }
      configuracoes_audit: {
        Row: {
          chave: string
          criado_em: string
          id: number
          operacao: string
          usuario_id: string | null
          usuario_role: string | null
          valor_antes: string | null
          valor_depois: string | null
        }
        Insert: {
          chave: string
          criado_em?: string
          id?: number
          operacao: string
          usuario_id?: string | null
          usuario_role?: string | null
          valor_antes?: string | null
          valor_depois?: string | null
        }
        Update: {
          chave?: string
          criado_em?: string
          id?: number
          operacao?: string
          usuario_id?: string | null
          usuario_role?: string | null
          valor_antes?: string | null
          valor_depois?: string | null
        }
        Relationships: []
      }
      faturacao_clientes: {
        Row: {
          componentes_jsonb: Json | null
          criado_em: string
          id: string
          id_cliente: string
          kwh_faturado: number
          leitura_final: number | null
          leitura_inicial: number | null
          mes_ano: string
          numero_fatura: string | null
          periodo_fim: string | null
          periodo_inicio: string | null
          saldo_anterior_cve: number | null
          saldo_atual_cve: number | null
          tipo_leitura: Database["public"]["Enums"]["tipo_leitura_enum"] | null
          valor_cve: number
        }
        Insert: {
          componentes_jsonb?: Json | null
          criado_em?: string
          id?: string
          id_cliente: string
          kwh_faturado: number
          leitura_final?: number | null
          leitura_inicial?: number | null
          mes_ano: string
          numero_fatura?: string | null
          periodo_fim?: string | null
          periodo_inicio?: string | null
          saldo_anterior_cve?: number | null
          saldo_atual_cve?: number | null
          tipo_leitura?: Database["public"]["Enums"]["tipo_leitura_enum"] | null
          valor_cve: number
        }
        Update: {
          componentes_jsonb?: Json | null
          criado_em?: string
          id?: string
          id_cliente?: string
          kwh_faturado?: number
          leitura_final?: number | null
          leitura_inicial?: number | null
          mes_ano?: string
          numero_fatura?: string | null
          periodo_fim?: string | null
          periodo_inicio?: string | null
          saldo_anterior_cve?: number | null
          saldo_atual_cve?: number | null
          tipo_leitura?: Database["public"]["Enums"]["tipo_leitura_enum"] | null
          valor_cve?: number
        }
        Relationships: [
          {
            foreignKeyName: "faturacao_clientes_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      importacoes: {
        Row: {
          criado_em: string
          erros_json: Json | null
          id: string
          id_utilizador: string
          nome_ficheiro: string
          registos_erro: number
          registos_sucesso: number
          tipo: string
          total_registos: number
        }
        Insert: {
          criado_em?: string
          erros_json?: Json | null
          id?: string
          id_utilizador: string
          nome_ficheiro: string
          registos_erro?: number
          registos_sucesso?: number
          tipo: string
          total_registos?: number
        }
        Update: {
          criado_em?: string
          erros_json?: Json | null
          id?: string
          id_utilizador?: string
          nome_ficheiro?: string
          registos_erro?: number
          registos_sucesso?: number
          tipo?: string
          total_registos?: number
        }
        Relationships: [
          {
            foreignKeyName: "importacoes_id_utilizador_fkey"
            columns: ["id_utilizador"]
            isOneToOne: false
            referencedRelation: "perfis"
            referencedColumns: ["id"]
          },
        ]
      }
      injecao_energia: {
        Row: {
          criado_em: string
          id: string
          id_subestacao: string
          mes_ano: string
          total_kwh_injetado: number
        }
        Insert: {
          criado_em?: string
          id?: string
          id_subestacao: string
          mes_ano: string
          total_kwh_injetado: number
        }
        Update: {
          criado_em?: string
          id?: string
          id_subestacao?: string
          mes_ano?: string
          total_kwh_injetado?: number
        }
        Relationships: [
          {
            foreignKeyName: "injecao_energia_id_subestacao_fkey"
            columns: ["id_subestacao"]
            isOneToOne: false
            referencedRelation: "subestacoes"
            referencedColumns: ["id"]
          },
        ]
      }
      ml_predicoes: {
        Row: {
          criado_em: string
          features_json: Json
          id: string
          id_cliente: string
          mes_ano: string
          modelo_versao: string
          score_ml: number
        }
        Insert: {
          criado_em?: string
          features_json: Json
          id?: string
          id_cliente: string
          mes_ano: string
          modelo_versao: string
          score_ml: number
        }
        Update: {
          criado_em?: string
          features_json?: Json
          id?: string
          id_cliente?: string
          mes_ano?: string
          modelo_versao?: string
          score_ml?: number
        }
        Relationships: [
          {
            foreignKeyName: "ml_predicoes_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      perfis: {
        Row: {
          ativo: boolean
          atualizado_em: string
          criado_em: string
          id: string
          id_zona: string | null
          nome_completo: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          ativo?: boolean
          atualizado_em?: string
          criado_em?: string
          id: string
          id_zona?: string | null
          nome_completo: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          ativo?: boolean
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_zona?: string | null
          nome_completo?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: []
      }
      relatorios_inspecao: {
        Row: {
          criado_em: string
          foto_lat: number | null
          foto_lng: number | null
          foto_url: string | null
          id: string
          id_alerta: string
          id_fiscal: string
          observacoes: string | null
          resultado: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Insert: {
          criado_em?: string
          foto_lat?: number | null
          foto_lng?: number | null
          foto_url?: string | null
          id?: string
          id_alerta: string
          id_fiscal: string
          observacoes?: string | null
          resultado: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude?: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Update: {
          criado_em?: string
          foto_lat?: number | null
          foto_lng?: number | null
          foto_url?: string | null
          id?: string
          id_alerta?: string
          id_fiscal?: string
          observacoes?: string | null
          resultado?: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude?: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Relationships: [
          {
            foreignKeyName: "relatorios_inspecao_id_alerta_fkey"
            columns: ["id_alerta"]
            isOneToOne: false
            referencedRelation: "alertas_fraude"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "relatorios_inspecao_id_fiscal_fkey"
            columns: ["id_fiscal"]
            isOneToOne: false
            referencedRelation: "perfis"
            referencedColumns: ["id"]
          },
        ]
      }
      subestacoes: {
        Row: {
          ativo: boolean
          capacidade_kwh: number | null
          criado_em: string
          id: string
          ilha: Database["public"]["Enums"]["ilha"]
          lat: number
          lng: number
          nome: string
          zona_bairro: string
        }
        Insert: {
          ativo?: boolean
          capacidade_kwh?: number | null
          criado_em?: string
          id?: string
          ilha?: Database["public"]["Enums"]["ilha"]
          lat: number
          lng: number
          nome: string
          zona_bairro: string
        }
        Update: {
          ativo?: boolean
          capacidade_kwh?: number | null
          criado_em?: string
          id?: string
          ilha?: Database["public"]["Enums"]["ilha"]
          lat?: number
          lng?: number
          nome?: string
          zona_bairro?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      get_user_zona: { Args: never; Returns: string }
    }
    Enums: {
      alerta_status:
        | "Pendente"
        | "Notificado_SMS"
        | "Pendente_Inspecao"
        | "Inspecionado"
      ilha:
        | "Santiago"
        | "Sao_Vicente"
        | "Sal"
        | "Santo_Antao"
        | "Fogo"
        | "Brava"
        | "Maio"
        | "Boa_Vista"
        | "Sao_Nicolau"
        | "Sao_Filipe"
      inspecao_resultado:
        | "Fraude_Confirmada"
        | "Anomalia_Tecnica"
        | "Falso_Positivo"
      tipo_fraude:
        | "Bypass"
        | "Contador_adulterado"
        | "Ligacao_vizinha"
        | "Ima"
        | "Outro"
      tipo_leitura_enum: "real" | "estimada" | "empresa" | "cliente"
      tipo_tarifa:
        | "Residencial"
        | "Comercial"
        | "Industrial"
        | "Servicos_Publicos"
      user_role:
        | "admin_fiskix"
        | "diretor"
        | "gestor_perdas"
        | "supervisor"
        | "fiscal"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      alerta_status: [
        "Pendente",
        "Notificado_SMS",
        "Pendente_Inspecao",
        "Inspecionado",
      ],
      ilha: [
        "Santiago",
        "Sao_Vicente",
        "Sal",
        "Santo_Antao",
        "Fogo",
        "Brava",
        "Maio",
        "Boa_Vista",
        "Sao_Nicolau",
        "Sao_Filipe",
      ],
      inspecao_resultado: [
        "Fraude_Confirmada",
        "Anomalia_Tecnica",
        "Falso_Positivo",
      ],
      tipo_fraude: [
        "Bypass",
        "Contador_adulterado",
        "Ligacao_vizinha",
        "Ima",
        "Outro",
      ],
      tipo_leitura_enum: ["real", "estimada", "empresa", "cliente"],
      tipo_tarifa: [
        "Residencial",
        "Comercial",
        "Industrial",
        "Servicos_Publicos",
      ],
      user_role: [
        "admin_fiskix",
        "diretor",
        "gestor_perdas",
        "supervisor",
        "fiscal",
      ],
    },
  },
} as const

// Convenience type aliases (derived from generated Database type)
export type UserRole = Database["public"]["Enums"]["user_role"]
export type AlertaStatus = Database["public"]["Enums"]["alerta_status"]
export type InspecaoResultado = Database["public"]["Enums"]["inspecao_resultado"]
export type TipoFraude = Database["public"]["Enums"]["tipo_fraude"]
export type TipoTarifa = Database["public"]["Enums"]["tipo_tarifa"]
export type Ilha = Database["public"]["Enums"]["ilha"]
export type TipoLeitura = Database["public"]["Enums"]["tipo_leitura_enum"]

// Application-level type for JSONB motivo field
export type RegraMotivo = {
  regra: string
  pontos: number
  descricao: string
  valor?: number
  threshold?: number
}
