// Auto-generated by Supabase CLI — do not edit manually
// Project: fiskix (rqplobwsdbceuqhjywgt)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      alertas_fraude: {
        Row: {
          atualizado_em: string
          criado_em: string
          id: string
          id_cliente: string
          mes_ano: string
          motivo: Json
          resultado: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco: number
          status: Database["public"]["Enums"]["alerta_status"]
        }
        Insert: {
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_cliente: string
          mes_ano: string
          motivo?: Json
          resultado?: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco: number
          status?: Database["public"]["Enums"]["alerta_status"]
        }
        Update: {
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_cliente?: string
          mes_ano?: string
          motivo?: Json
          resultado?: Database["public"]["Enums"]["inspecao_resultado"] | null
          score_risco?: number
          status?: Database["public"]["Enums"]["alerta_status"]
        }
        Relationships: [
          {
            foreignKeyName: "alertas_fraude_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      clientes: {
        Row: {
          ativo: boolean
          criado_em: string
          id: string
          id_subestacao: string
          lat: number | null
          lng: number | null
          morada: string
          nome_titular: string
          numero_contador: string
          telemovel: string | null
          tipo_tarifa: Database["public"]["Enums"]["tipo_tarifa"]
        }
        Insert: {
          ativo?: boolean
          criado_em?: string
          id?: string
          id_subestacao: string
          lat?: number | null
          lng?: number | null
          morada: string
          nome_titular: string
          numero_contador: string
          telemovel?: string | null
          tipo_tarifa?: Database["public"]["Enums"]["tipo_tarifa"]
        }
        Update: {
          ativo?: boolean
          criado_em?: string
          id?: string
          id_subestacao?: string
          lat?: number | null
          lng?: number | null
          morada?: string
          nome_titular?: string
          numero_contador?: string
          telemovel?: string | null
          tipo_tarifa?: Database["public"]["Enums"]["tipo_tarifa"]
        }
        Relationships: [
          {
            foreignKeyName: "clientes_id_subestacao_fkey"
            columns: ["id_subestacao"]
            isOneToOne: false
            referencedRelation: "subestacoes"
            referencedColumns: ["id"]
          },
        ]
      }
      configuracoes: {
        Row: {
          atualizado_em: string
          chave: string
          descricao: string | null
          valor: string
        }
        Insert: {
          atualizado_em?: string
          chave: string
          descricao?: string | null
          valor: string
        }
        Update: {
          atualizado_em?: string
          chave?: string
          descricao?: string | null
          valor?: string
        }
        Relationships: []
      }
      faturacao_clientes: {
        Row: {
          criado_em: string
          id: string
          id_cliente: string
          kwh_faturado: number
          mes_ano: string
          valor_cve: number
        }
        Insert: {
          criado_em?: string
          id?: string
          id_cliente: string
          kwh_faturado: number
          mes_ano: string
          valor_cve: number
        }
        Update: {
          criado_em?: string
          id?: string
          id_cliente?: string
          kwh_faturado?: number
          mes_ano?: string
          valor_cve?: number
        }
        Relationships: [
          {
            foreignKeyName: "faturacao_clientes_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      importacoes: {
        Row: {
          criado_em: string
          erros_json: Json | null
          id: string
          id_utilizador: string
          nome_ficheiro: string
          registos_erro: number
          registos_sucesso: number
          tipo: string
          total_registos: number
        }
        Insert: {
          criado_em?: string
          erros_json?: Json | null
          id?: string
          id_utilizador: string
          nome_ficheiro: string
          registos_erro?: number
          registos_sucesso?: number
          tipo: string
          total_registos?: number
        }
        Update: {
          criado_em?: string
          erros_json?: Json | null
          id?: string
          id_utilizador?: string
          nome_ficheiro?: string
          registos_erro?: number
          registos_sucesso?: number
          tipo?: string
          total_registos?: number
        }
        Relationships: [
          {
            foreignKeyName: "importacoes_id_utilizador_fkey"
            columns: ["id_utilizador"]
            isOneToOne: false
            referencedRelation: "perfis"
            referencedColumns: ["id"]
          },
        ]
      }
      injecao_energia: {
        Row: {
          criado_em: string
          id: string
          id_subestacao: string
          mes_ano: string
          total_kwh_injetado: number
        }
        Insert: {
          criado_em?: string
          id?: string
          id_subestacao: string
          mes_ano: string
          total_kwh_injetado: number
        }
        Update: {
          criado_em?: string
          id?: string
          id_subestacao?: string
          mes_ano?: string
          total_kwh_injetado?: number
        }
        Relationships: [
          {
            foreignKeyName: "injecao_energia_id_subestacao_fkey"
            columns: ["id_subestacao"]
            isOneToOne: false
            referencedRelation: "subestacoes"
            referencedColumns: ["id"]
          },
        ]
      }
      ml_predicoes: {
        Row: {
          criado_em: string
          features_json: Json
          id: string
          id_cliente: string
          mes_ano: string
          modelo_versao: string
          score_ml: number
        }
        Insert: {
          criado_em?: string
          features_json: Json
          id?: string
          id_cliente: string
          mes_ano: string
          modelo_versao: string
          score_ml: number
        }
        Update: {
          criado_em?: string
          features_json?: Json
          id?: string
          id_cliente?: string
          mes_ano?: string
          modelo_versao?: string
          score_ml?: number
        }
        Relationships: [
          {
            foreignKeyName: "ml_predicoes_id_cliente_fkey"
            columns: ["id_cliente"]
            isOneToOne: false
            referencedRelation: "clientes"
            referencedColumns: ["id"]
          },
        ]
      }
      perfis: {
        Row: {
          ativo: boolean
          atualizado_em: string
          criado_em: string
          id: string
          id_zona: string | null
          nome_completo: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          ativo?: boolean
          atualizado_em?: string
          criado_em?: string
          id: string
          id_zona?: string | null
          nome_completo: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          ativo?: boolean
          atualizado_em?: string
          criado_em?: string
          id?: string
          id_zona?: string | null
          nome_completo?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: []
      }
      relatorios_inspecao: {
        Row: {
          criado_em: string
          foto_lat: number | null
          foto_lng: number | null
          foto_url: string | null
          id: string
          id_alerta: string
          id_fiscal: string
          observacoes: string | null
          resultado: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Insert: {
          criado_em?: string
          foto_lat?: number | null
          foto_lng?: number | null
          foto_url?: string | null
          id?: string
          id_alerta: string
          id_fiscal: string
          observacoes?: string | null
          resultado: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude?: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Update: {
          criado_em?: string
          foto_lat?: number | null
          foto_lng?: number | null
          foto_url?: string | null
          id?: string
          id_alerta?: string
          id_fiscal?: string
          observacoes?: string | null
          resultado?: Database["public"]["Enums"]["inspecao_resultado"]
          tipo_fraude?: Database["public"]["Enums"]["tipo_fraude"] | null
        }
        Relationships: [
          {
            foreignKeyName: "relatorios_inspecao_id_alerta_fkey"
            columns: ["id_alerta"]
            isOneToOne: false
            referencedRelation: "alertas_fraude"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "relatorios_inspecao_id_fiscal_fkey"
            columns: ["id_fiscal"]
            isOneToOne: false
            referencedRelation: "perfis"
            referencedColumns: ["id"]
          },
        ]
      }
      subestacoes: {
        Row: {
          ativo: boolean
          capacidade_kwh: number | null
          criado_em: string
          id: string
          ilha: Database["public"]["Enums"]["ilha"]
          lat: number
          lng: number
          nome: string
          zona_bairro: string
        }
        Insert: {
          ativo?: boolean
          capacidade_kwh?: number | null
          criado_em?: string
          id?: string
          ilha?: Database["public"]["Enums"]["ilha"]
          lat: number
          lng: number
          nome: string
          zona_bairro: string
        }
        Update: {
          ativo?: boolean
          capacidade_kwh?: number | null
          criado_em?: string
          id?: string
          ilha?: Database["public"]["Enums"]["ilha"]
          lat?: number
          lng?: number
          nome?: string
          zona_bairro?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      get_user_zona: { Args: never; Returns: string }
    }
    Enums: {
      alerta_status: "Pendente" | "Notificado_SMS" | "Pendente_Inspecao" | "Inspecionado"
      ilha: "Santiago" | "Sao_Vicente" | "Sal" | "Santo_Antao" | "Fogo" | "Brava" | "Maio" | "Boa_Vista" | "Sao_Nicolau" | "Sao_Filipe"
      inspecao_resultado: "Fraude_Confirmada" | "Anomalia_Tecnica" | "Falso_Positivo"
      tipo_fraude: "Bypass" | "Contador_adulterado" | "Ligacao_vizinha" | "Ima" | "Outro"
      tipo_tarifa: "Residencial" | "Comercial" | "Industrial" | "Servicos_Publicos"
      user_role: "admin_fiskix" | "diretor" | "gestor_perdas" | "supervisor" | "fiscal"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience type aliases (derived from generated Database type)
export type UserRole = Database["public"]["Enums"]["user_role"]
export type AlertaStatus = Database["public"]["Enums"]["alerta_status"]
export type InspecaoResultado = Database["public"]["Enums"]["inspecao_resultado"]
export type TipoFraude = Database["public"]["Enums"]["tipo_fraude"]
export type TipoTarifa = Database["public"]["Enums"]["tipo_tarifa"]
export type Ilha = Database["public"]["Enums"]["ilha"]

// Application-level type for JSONB motivo field
export type RegraMotivo = {
  regra: string
  pontos: number
  descricao: string
  valor?: number
  threshold?: number
}
